name: Build ISO
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: export NIXPKGS_ALLOW_UNFREE=1
    - run: nix-build .#nixosConfigurations.laptopISO.config.system.build.isoImage
