name: Build ISO
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Magic Nix Cache
      # You may pin to the exact commit or the version.
      # uses: DeterminateSystems/magic-nix-cache-action@87e8236f46702ab0ce5a058b605a173ec88d618e
      uses: DeterminateSystems/magic-nix-cache-action@v6
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: export NIXPKGS_ALLOW_UNFREE=1
    - run: nix build .#nixosConfigurations.laptopISO.config.system.build.isoImage
